[DEFAULT]
sign-tags = False
pristine-tar = False

[import-orig]
postunpack= mkdir -p "$GBP_SOURCES_DIR-new" && mv "$GBP_SOURCES_DIR" "$GBP_SOURCES_DIR-new/src" && mv "$GBP_SOURCES_DIR-new" "$GBP_SOURCES_DIR"
